Repository Intel-bigdata/OAP, pull requests merged in 2020-06, with the labels that each got.

#1342 [CI] update to use new oap-master branch
  .travis.yml
Labels: NativeSQL

#1338 [RDD cache PMem extension] [POAE7-316] Move RDD cache PMem extension into OAP project - initial part
  dev/Apply_Spark_changes.sh
  dev/changes_list/spark_changed_files
  oap-spark/.gitignore
  oap-spark/README.md
  oap-spark/pom.xml
  oap-spark/src/main/java/org/apache/spark/memory/MemoryMode.java
  oap-spark/src/main/scala/org/apache/spark/SparkEnv.scala
  oap-spark/src/main/scala/org/apache/spark/memory/MemoryManager.scala
  oap-spark/src/main/scala/org/apache/spark/memory/StorageMemoryPool.scala
  oap-spark/src/main/scala/org/apache/spark/memory/UnifiedMemoryManager.scala
  oap-spark/src/main/scala/org/apache/spark/storage/BlockManager.scala
  oap-spark/src/main/scala/org/apache/spark/storage/StorageLevel.scala
  oap-spark/src/test/scala/org/apache/spark/memory/TestMemoryManager.scala
  pom.xml
Labels: ElasticDataFusion

#1349 [POAE7-323] fix numa changes in RDD Cache
  oap-spark/.gitignore
  oap-spark/README.md
  oap-spark/pom.xml
  oap-spark/src/main/scala/org/apache/spark/SparkEnv.scala
  oap-spark/src/main/scala/org/apache/spark/memory/StaticMemoryManager.scala
  oap-spark/src/main/scala/org/apache/spark/memory/UnifiedMemoryManager.scala
  oap-spark/src/main/scala/org/apache/spark/storage/memory/MemoryStore.scala
  pom.xml
Labels: ElasticDataFusion

#1313 POAE7-319: reader/writer for memkind
  .travis.yml
  oap-common/src/main/java/com/intel/oap/common/storage/memkind/MemkindChunkReader.java
  oap-common/src/main/java/com/intel/oap/common/storage/memkind/MemkindChunkWriter.java
  oap-common/src/main/java/com/intel/oap/common/storage/memkind/MemkindMetaStore.java
  oap-common/src/main/java/com/intel/oap/common/storage/memkind/MemkindPMemPhysicalAddress.java
  oap-common/src/main/java/com/intel/oap/common/storage/stream/ChunkInputStream.java
  oap-common/src/main/java/com/intel/oap/common/storage/stream/ChunkOutputStream.java
  oap-common/src/main/java/com/intel/oap/common/storage/stream/ChunkReader.java
  oap-common/src/main/java/com/intel/oap/common/storage/stream/ChunkWriter.java
  oap-common/src/main/java/com/intel/oap/common/storage/stream/PMemMetaStore.java
  oap-common/src/main/java/com/intel/oap/common/util/MemCopyUtil.java
  oap-common/src/test/java/com/intel/oap/common/storage/ChunkStreamAPITest.java
Labels: ElasticDataFusion

#1324 [oap-native-sql]Rewrite ColumnarShuffledHashJoin using CodeGeneration
  oap-native-sql/core/pom.xml
  oap-native-sql/core/src/main/java/com/intel/sparkColumnarPlugin/vectorized/ExpressionEvaluator.java
  oap-native-sql/core/src/main/java/com/intel/sparkColumnarPlugin/vectorized/ExpressionEvaluatorJniWrapper.java
  oap-native-sql/core/src/main/java/com/intel/sparkColumnarPlugin/vectorized/JniUtils.java
  oap-native-sql/core/src/main/scala/com/intel/sparkColumnarPlugin/expression/ColumnarShuffledHashJoin.scala
  oap-native-sql/cpp/src/CMakeLists.txt
  oap-native-sql/cpp/src/benchmarks/arrow_compute_benchmark_join.cc
  oap-native-sql/cpp/src/benchmarks/make.sh
  oap-native-sql/cpp/src/codegen/arrow_compute/expr_visitor.cc
  oap-native-sql/cpp/src/codegen/arrow_compute/expr_visitor_impl.h
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/array_item_index.h
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/code_generator_base.h
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/codegen_common.cc
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/codegen_common.h
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/codegen_node_visitor.cc
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/codegen_node_visitor.h
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/codegen_node_visitor_v2.cc
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/codegen_node_visitor_v2.h
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/conditioned_probe_kernel.cc
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/conditioned_shuffle_kernel.cc
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/conditioner.h
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/item_iterator.cc
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/item_iterator.h
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/kernels_ext.cc
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/kernels_ext.h
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/probe_kernel.cc
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/shuffle_v2_action.cc
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/shuffle_v2_action.h
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/sort_kernel.cc
  oap-native-sql/cpp/src/codegen/common/result_iterator.h
  oap-native-sql/cpp/src/jni/jni_wrapper.cc
  oap-native-sql/cpp/src/tests/arrow_compute_test_join.cc
  oap-native-sql/cpp/src/third_party/sparsehash/dense_hash_map
  oap-native-sql/cpp/src/third_party/sparsehash/dense_hash_set
  oap-native-sql/cpp/src/third_party/sparsehash/internal/densehashtable.h
  oap-native-sql/cpp/src/third_party/sparsehash/internal/hashtable-common.h
  oap-native-sql/cpp/src/third_party/sparsehash/internal/libc_allocator_with_realloc.h
  oap-native-sql/cpp/src/third_party/sparsehash/internal/sparsehashtable.h
  oap-native-sql/cpp/src/third_party/sparsehash/sparse_hash_map
  oap-native-sql/cpp/src/third_party/sparsehash/sparse_hash_map.h
  oap-native-sql/cpp/src/third_party/sparsehash/sparse_hash_set
  oap-native-sql/cpp/src/third_party/sparsehash/sparsetable
  oap-native-sql/cpp/src/third_party/sparsehash/traits
  oap-native-sql/cpp/src/utils/macros.h
Labels: NativeSQL

#1328 [oap-native-sql][Scala] adding concat support
  oap-native-sql/core/src/main/scala/com/intel/sparkColumnarPlugin/expression/ColumnarConcatOperator.scala
  oap-native-sql/core/src/main/scala/com/intel/sparkColumnarPlugin/expression/ColumnarExpressionConverter.scala
Labels: NativeSQL

#1340 [oap-native-sql][Scala] refine coalesce
  oap-native-sql/core/src/main/scala/com/intel/sparkColumnarPlugin/expression/ColumnarCoalesceOperator.scala
Labels: NativeSQL

#1333 [oap-native-sql][Scala] bypass nullPointerException
  oap-native-sql/core/src/main/scala/com/intel/sparkColumnarPlugin/expression/ColumnarLiterals.scala
  oap-native-sql/core/src/main/scala/com/intel/sparkColumnarPlugin/expression/ColumnarSubquery.scala
Labels: NativeSQL

#1341 [oap-native-sql] Enable mvn package to build native libs
  oap-native-sql/core/pom.xml
  oap-native-sql/cpp/compile.sh
Labels: NativeSQL

#1330 [oap-native-sql][Scala] fix attr errors
  oap-native-sql/core/src/main/scala/com/intel/sparkColumnarPlugin/expression/ConverterUtils.scala
Labels: NativeSQL

#1332 [oap-native-sql][Scala] adding round support
  oap-native-sql/core/src/main/scala/com/intel/sparkColumnarPlugin/expression/ColumnarExpressionConverter.scala
  oap-native-sql/core/src/main/scala/com/intel/sparkColumnarPlugin/expression/ColumnarRoundOperator.scala
Labels: NativeSQL

#1359 [CI] fix travis to use oap-master branch of arrow
  .travis.yml
Labels: NativeSQL

#1212 [oap-native-sql] columnar shuffle
  .travis.yml
  oap-native-sql/README.md
  oap-native-sql/core/pom.xml
  oap-native-sql/core/src/main/java/com/intel/sparkColumnarPlugin/vectorized/AdaptorReferenceManager.java
  oap-native-sql/core/src/main/java/com/intel/sparkColumnarPlugin/vectorized/PartitionFileInfo.java
  oap-native-sql/core/src/main/java/com/intel/sparkColumnarPlugin/vectorized/ShuffleDecompressionJniWrapper.java
  oap-native-sql/core/src/main/java/com/intel/sparkColumnarPlugin/vectorized/ShuffleSplitterJniWrapper.java
  oap-native-sql/core/src/main/scala/com/intel/sparkColumnarPlugin/ColumnarPlugin.scala
  oap-native-sql/core/src/main/scala/com/intel/sparkColumnarPlugin/ColumnarPluginConfig.scala
  oap-native-sql/core/src/main/scala/com/intel/sparkColumnarPlugin/execution/CoalesceBatchesExec.scala
  oap-native-sql/core/src/main/scala/com/intel/sparkColumnarPlugin/vectorized/ArrowColumnarBatchSerializer.scala
  oap-native-sql/core/src/main/scala/org/apache/spark/shuffle/ColumnarShuffleDependency.scala
  oap-native-sql/core/src/main/scala/org/apache/spark/shuffle/ColumnarShuffleWriter.scala
  oap-native-sql/core/src/main/scala/org/apache/spark/shuffle/sort/ColumnarShuffleManager.scala
  oap-native-sql/core/src/main/scala/org/apache/spark/sql/execution/ColumnarShuffleExchangeExec.scala
  oap-native-sql/core/src/test/resources/part-00000-d648dd34-c9d2-4fe9-87f2-770ef3551442-c000.snappy.parquet
  oap-native-sql/core/src/test/scala/com.intel.sparkColumnarPlugin/ExtensionSuite.scala
  oap-native-sql/core/src/test/scala/org/apache/spark/shuffle/ColumnarShuffleWriterSuite.scala
  oap-native-sql/core/src/test/scala/org/apache/spark/sql/RepartitionSuite.scala
  oap-native-sql/cpp/.gitignore
  oap-native-sql/cpp/src/CMakeLists.txt
  oap-native-sql/cpp/src/jni/jni_common.h
  oap-native-sql/cpp/src/jni/jni_wrapper.cc
  oap-native-sql/cpp/src/shuffle/partition_writer.cc
  oap-native-sql/cpp/src/shuffle/partition_writer.h
  oap-native-sql/cpp/src/shuffle/splitter.cc
  oap-native-sql/cpp/src/shuffle/splitter.h
  oap-native-sql/cpp/src/shuffle/type.h
  oap-native-sql/cpp/src/tests/CMakeLists.txt
  oap-native-sql/cpp/src/tests/shuffle_split_test.cc
Labels: NativeSQL

#1364 [oap-cache] update user guide based on feedback from users
  oap-cache/oap/docs/OAP-Cache-User-Guide.md
Labels: Oap Cache

#1362 [oap-native-sql] Add customized batch_size and tmp_dir support
  oap-native-sql/core/src/main/java/com/intel/sparkColumnarPlugin/datasource/VectorizedParquetArrowReader.java
  oap-native-sql/core/src/main/java/com/intel/sparkColumnarPlugin/datasource/parquet/ParquetReader.java
  oap-native-sql/core/src/main/java/com/intel/sparkColumnarPlugin/datasource/parquet/ParquetReaderJniWrapper.java
  oap-native-sql/core/src/main/java/com/intel/sparkColumnarPlugin/vectorized/ExpressionEvaluator.java
  oap-native-sql/core/src/main/java/com/intel/sparkColumnarPlugin/vectorized/ExpressionEvaluatorJniWrapper.java
  oap-native-sql/core/src/main/java/com/intel/sparkColumnarPlugin/vectorized/JniUtils.java
  oap-native-sql/core/src/main/scala/com/intel/sparkColumnarPlugin/ColumnarPluginConfig.scala
  oap-native-sql/core/src/main/scala/com/intel/sparkColumnarPlugin/execution/ColumnarBatchScanExec.scala
  oap-native-sql/core/src/main/scala/com/intel/sparkColumnarPlugin/execution/ColumnarDataSourceRDD.scala
  oap-native-sql/core/src/main/scala/com/intel/sparkColumnarPlugin/execution/ColumnarHashAggregateExec.scala
  oap-native-sql/core/src/main/scala/com/intel/sparkColumnarPlugin/execution/ColumnarShuffledHashJoinExec.scala
  oap-native-sql/core/src/main/scala/com/intel/sparkColumnarPlugin/execution/ColumnarSortExec.scala
  oap-native-sql/core/src/main/scala/com/intel/sparkColumnarPlugin/expression/ColumnarAggregation.scala
  oap-native-sql/core/src/main/scala/com/intel/sparkColumnarPlugin/expression/ColumnarShuffledHashJoin.scala
  oap-native-sql/core/src/main/scala/com/intel/sparkColumnarPlugin/expression/ColumnarSorter.scala
  oap-native-sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/v2/VectorizedFilePartitionReaderHandler.scala
  oap-native-sql/core/src/test/java/com/intel/sparkColumnarPlugin/datasource/parquet/ParquetReadTest.java
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/codegen_common.cc
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/codegen_common.h
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/kernels_ext.cc
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/sort_kernel.cc
  oap-native-sql/cpp/src/jni/jni_wrapper.cc
Labels: NativeSQL

#1372 [oap-native-sql]Wip optimize sort
  oap-native-sql/cpp/src/benchmarks/arrow_compute_benchmark_sort.cc
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/codegen_common.cc
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/sort_kernel.cc
  oap-native-sql/cpp/src/third_party/ska_sort.hpp
Labels: NativeSQL

#1378 [oap-native-sql] Columnar shuffle I/O Use Configured Disks
  oap-native-sql/core/src/main/java/com/intel/sparkColumnarPlugin/vectorized/ShuffleSplitterJniWrapper.java
  oap-native-sql/core/src/main/scala/org/apache/spark/shuffle/ColumnarShuffleWriter.scala
  oap-native-sql/core/src/main/scala/org/apache/spark/sql/execution/ColumnarShuffleExchangeExec.scala
  oap-native-sql/core/src/test/scala/org/apache/spark/sql/RepartitionSuite.scala
  oap-native-sql/cpp/src/jni/jni_wrapper.cc
  oap-native-sql/cpp/src/shuffle/splitter.cc
  oap-native-sql/cpp/src/tests/shuffle_split_test.cc
  oap-native-sql/resource/ApacheArrowInstallation.md
Labels: NativeSQL

#1377 [oap-native-sql][C++] opt hash join
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/codegen_common.cc
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/kernels_ext.cc
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/probe_kernel.cc
Labels: NativeSQL

#1381 [NativeSql][Scala] compression workaround
  oap-native-sql/README.md
  oap-native-sql/core/src/main/java/com/intel/sparkColumnarPlugin/vectorized/ArrowCompressedStreamReader.java
  oap-native-sql/core/src/main/java/com/intel/sparkColumnarPlugin/vectorized/CompressedVectorLoader.java
  oap-native-sql/core/src/main/scala/com/intel/sparkColumnarPlugin/vectorized/ArrowColumnarBatchSerializer.scala
  oap-native-sql/core/src/test/scala/org/apache/spark/shuffle/ColumnarShuffleWriterSuite.scala
  oap-native-sql/core/src/test/scala/org/apache/spark/sql/RepartitionSuite.scala
  oap-native-sql/cpp/src/shuffle/splitter.cc
Labels: NativeSQL

#1376 [DataSource][Arrow] Support reading dictionary encoded parquet values
  .travis.yml
  oap-data-source/arrow/pom.xml
  oap-data-source/arrow/src/main/scala/com/intel/oap/spark/sql/execution/datasources/arrow/ArrowFileFormat.scala
  oap-data-source/arrow/src/main/scala/com/intel/oap/spark/sql/execution/datasources/v2/arrow/ArrowPartitionReaderFactory.scala
  oap-data-source/arrow/src/main/scala/org/apache/spark/sql/execution/datasources/v2/arrow/ArrowUtils.scala
  oap-data-source/arrow/src/test/scala/com/intel/oap/spark/sql/execution/datasources/arrow/ArrowDataSourceTest.scala
  oap-native-sql/core/src/main/java/com/intel/sparkColumnarPlugin/vectorized/ArrowWritableColumnVector.java
Labels: NativeSQL

#1367 [POAE7-335] libpmemblk backend and libpmemkv metastore implementation
  .travis.yml
  dev/install_pmdk.sh
  dev/install_pmemkv.sh
  oap-common/.gitignore
  oap-common/pom.xml
  oap-common/src/main/java/com/intel/oap/common/storage/memkind/MemkindChunkReader.java
  oap-common/src/main/java/com/intel/oap/common/storage/memkind/MemkindMetaStore.java
  oap-common/src/main/java/com/intel/oap/common/storage/pmemblk/PMemBlkChunkReader.java
  oap-common/src/main/java/com/intel/oap/common/storage/pmemblk/PMemBlkChunkWriter.java
  oap-common/src/main/java/com/intel/oap/common/storage/pmemblk/PMemBlkMetaStore.java
  oap-common/src/main/java/com/intel/oap/common/storage/pmemblk/PMemBlkPhysicalAddress.java
  oap-common/src/main/java/com/intel/oap/common/storage/pmemblk/PMemKVDatabase.java
  oap-common/src/main/java/com/intel/oap/common/storage/pmemblk/benchmark/PMemBlkPerfTool.java
  oap-common/src/main/java/com/intel/oap/common/storage/stream/ChunkReader.java
  oap-common/src/main/java/com/intel/oap/common/storage/stream/DataStore.java
  oap-common/src/main/java/com/intel/oap/common/storage/stream/PMemManager.java
  oap-common/src/main/java/com/intel/oap/common/storage/stream/PMemMetaStore.java
  oap-common/src/main/java/com/intel/oap/common/unsafe/PMemBlockPlatform.java
  oap-common/src/native/libpmemblk/CMakeLists.txt
  oap-common/src/native/libpmemblk/com_intel_oap_common_unsafe_PMemBlockPlatform.cpp
  oap-common/src/native/libpmemblk/com_intel_oap_common_unsafe_PMemBlockPlatform.h
  oap-common/src/native/libpmemblk/compile.sh
  oap-common/src/test/java/com/intel/oap/common/storage/ChunkStreamAPITest.java
  oap-common/src/test/java/com/intel/oap/common/storage/pmemblk/PMemBlkChunkReaderWriterTest.java
  oap-common/src/test/java/com/intel/oap/common/storage/pmemblk/PMemKVDatabaseTest.java
  oap-common/src/test/java/com/intel/oap/common/unsafe/PMemBlockPlatformTest.java
  pom.xml
Labels: ElasticDataFusion

#1385 [OAP-RPMemshuffle] RPMem shuffle Document update
  oap-shuffle/RPMem-shuffle/README.md
  oap-shuffle/RPMem-shuffle/doc/Spark-PMoF-enabling-guide.pdf
  oap-shuffle/RPMem-shuffle/doc/images/RPMem_shuffle_architecture.png
Labels: RPMemshuffle

#1391 Modify pom.xml to add RPMem shuffle as a sub project
  oap-shuffle/RPMem-shuffle/core/pom.xml
  oap-shuffle/RPMem-shuffle/native/pom.xml
  oap-shuffle/RPMem-shuffle/pom.xml
  pom.xml
Labels: RPMemshuffle

#1370 [oap-native-sql]Add ColumnarBatch Combination on Shuffle Read Side
  oap-native-sql/core/src/main/java/com/intel/sparkColumnarPlugin/vectorized/AdaptorReferenceManager.java
  oap-native-sql/core/src/main/java/com/intel/sparkColumnarPlugin/vectorized/ArrowCompressedStreamReader.java
  oap-native-sql/core/src/main/java/com/intel/sparkColumnarPlugin/vectorized/CompressedVectorLoader.java
  oap-native-sql/core/src/main/java/com/intel/sparkColumnarPlugin/vectorized/PartitionFileInfo.java
  oap-native-sql/core/src/main/java/com/intel/sparkColumnarPlugin/vectorized/ShuffleDecompressionJniWrapper.java
  oap-native-sql/core/src/main/java/com/intel/sparkColumnarPlugin/vectorized/ShuffleSplitterJniWrapper.java
  oap-native-sql/core/src/main/scala/com/intel/sparkColumnarPlugin/execution/CoalesceBatchesExec.scala
  oap-native-sql/core/src/main/scala/com/intel/sparkColumnarPlugin/expression/ConverterUtils.scala
  oap-native-sql/core/src/main/scala/com/intel/sparkColumnarPlugin/vectorized/ArrowColumnarBatchSerializer.scala
  oap-native-sql/core/src/main/scala/org/apache/spark/shuffle/ColumnarShuffleDependency.scala
  oap-native-sql/core/src/main/scala/org/apache/spark/shuffle/ColumnarShuffleWriter.scala
  oap-native-sql/core/src/main/scala/org/apache/spark/sql/execution/ColumnarShuffleExchangeExec.scala
  oap-native-sql/core/src/test/scala/org/apache/spark/shuffle/ColumnarShuffleWriterSuite.scala
  oap-native-sql/core/src/test/scala/org/apache/spark/sql/RepartitionSuite.scala
Labels: NativeSQL

#1394 [oap-native-sql] compression use single thread
  oap-native-sql/cpp/src/shuffle/partition_writer.cc
Labels: NativeSQL

#1395 [oap-native-sql][C++] extract codegen headers to nativesql_include folder
  oap-native-sql/core/src/main/java/com/intel/sparkColumnarPlugin/vectorized/JniUtils.java
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/codegen_common.cc
Labels: NativeSQL

#1398 [OAP-RPMemshuffle] Rename RPMem shuffle jar file
  oap-shuffle/RPMem-shuffle/core/pom.xml
Labels: RPMemshuffle

#1393 [DataSource][Arrow] Reserve buffer bytes from Spark off-heap executio…
  oap-data-source/arrow/src/main/scala/com/intel/oap/spark/sql/execution/datasources/arrow/ArrowFileFormat.scala
  oap-data-source/arrow/src/main/scala/com/intel/oap/spark/sql/execution/datasources/v2/arrow/ArrowPartitionReaderFactory.scala
  oap-data-source/arrow/src/main/scala/com/intel/oap/spark/sql/execution/datasources/v2/arrow/ArrowTable.scala
  oap-data-source/arrow/src/main/scala/com/intel/oap/spark/sql/execution/datasources/v2/arrow/ExecutionMemoryAllocationListener.scala
  oap-data-source/arrow/src/main/scala/org/apache/spark/sql/execution/datasources/v2/arrow/ArrowUtils.scala
  oap-data-source/arrow/src/test/scala/com/intel/oap/spark/sql/execution/datasources/arrow/ArrowDataSourceTPCHBasedTest.scala
  oap-data-source/arrow/src/test/scala/com/intel/oap/spark/sql/execution/datasources/arrow/ArrowDataSourceTest.scala
Labels: NativeSQL

#1392 [oap-native-sql][Doc] update docs
  oap-native-sql/README.md
  oap-native-sql/resource/Native_SQL_Engine_Intro.jpg
  oap-native-sql/resource/columnar.png
  oap-native-sql/resource/dataset.png
  oap-native-sql/resource/installation.md
  oap-native-sql/resource/kernel.png
  oap-native-sql/resource/nativesql_arch.png
  oap-native-sql/resource/shuffle.png
Labels: NativeSQL
