Repository Intel-bigdata/OAP, pull requests merged in 2020-05, with the labels that each got.

#1251 [NativeSql] googletest installation fixes
  oap-native-sql/README.md
Labels: NativeSQL

#1256 [oa-native-sql][Scala] adding IsNull support
  oap-native-sql/core/src/main/scala/com/intel/sparkColumnarPlugin/expression/ColumnarUnaryOperator.scala
Labels: NativeSQL

#1283 [Oap-Common] Support File Chunk
  oap-common/src/main/java/com/intel/oap/common/storage/Chunk.java
  oap-common/src/main/java/com/intel/oap/common/storage/FileChunk.java
  oap-common/src/main/java/com/intel/oap/common/storage/PMemChunk.java
  oap-common/src/main/java/com/intel/oap/common/storage/PMemDataStore.java
  oap-common/src/test/java/com/intel/oap/common/storage/FileChunkTest.java
Labels: ElasticDataFusion

#1266 [oap-native-sql] Add open permission parameter
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/conditioned_probe_kernel.cc
Labels: NativeSQL

#1273 [oap-native-sql][Scala]Adding abs support
  oap-native-sql/core/src/main/scala/com/intel/sparkColumnarPlugin/expression/ColumnarUnaryOperator.scala
Labels: NativeSQL

#1249 [oap-native-sql][Building] building with spark-sql from our maven repo
  oap-native-sql/core/pom.xml
Labels: NativeSQL

#1291 initial implementation for memkind
  oap-common/src/main/java/com/intel/oap/common/storage/Chunk.java
  oap-common/src/main/java/com/intel/oap/common/storage/ChunkAPI.java
  oap-common/src/main/java/com/intel/oap/common/storage/ChunkImplFactory.java
  oap-common/src/main/java/com/intel/oap/common/storage/ChunkManager.java
  oap-common/src/main/java/com/intel/oap/common/storage/FileChunk.java
  oap-common/src/main/java/com/intel/oap/common/storage/MemKindChunkAPIImpl.java
  oap-common/src/main/java/com/intel/oap/common/storage/MemKindChunkManagerImpl.java
  oap-common/src/main/java/com/intel/oap/common/storage/MemKindPMemDataStoreImpl.java
  oap-common/src/main/java/com/intel/oap/common/storage/MemoryCopyUtil.java
  oap-common/src/main/java/com/intel/oap/common/storage/PMemChunk.java
  oap-common/src/main/java/com/intel/oap/common/storage/PMemDataStore.java
  oap-common/src/main/java/com/intel/oap/common/storage/PMemManager.java
  oap-common/src/main/java/com/intel/oap/common/storage/SPDKChunkImpl.java
  oap-common/src/main/java/com/intel/oap/common/storage/StreamMeta.java
Labels: ElasticDataFusion

#1290 [oap-native-sql][Scala] adding inset support
  oap-native-sql/core/src/main/scala/com/intel/sparkColumnarPlugin/expression/ColumnarExpressionConverter.scala
  oap-native-sql/core/src/main/scala/com/intel/sparkColumnarPlugin/expression/ColumnarInSetOperator.scala
Labels: NativeSQL

#1293 [Oap-Common] Follow up using latest APIs introduced from Memkind Impl
  oap-common/src/main/java/com/intel/oap/common/storage/Chunk.java
  oap-common/src/main/java/com/intel/oap/common/storage/ChunkAPI.java
  oap-common/src/main/java/com/intel/oap/common/storage/ChunkImplFactory.java
  oap-common/src/main/java/com/intel/oap/common/storage/ChunkInputStream.java
  oap-common/src/main/java/com/intel/oap/common/storage/ChunkManager.java
  oap-common/src/main/java/com/intel/oap/common/storage/ChunkType.java
  oap-common/src/main/java/com/intel/oap/common/storage/FileChunk.java
  oap-common/src/main/java/com/intel/oap/common/storage/MemKindChunkAPIImpl.java
  oap-common/src/main/java/com/intel/oap/common/storage/MemKindChunkManagerImpl.java
  oap-common/src/main/java/com/intel/oap/common/storage/MemKindPMemDataStoreImpl.java
  oap-common/src/main/java/com/intel/oap/common/storage/MemoryCopyUtil.java
  oap-common/src/main/java/com/intel/oap/common/storage/PMemChunk.java
  oap-common/src/main/java/com/intel/oap/common/storage/PMemDataStore.java
  oap-common/src/main/java/com/intel/oap/common/storage/PMemManager.java
  oap-common/src/main/java/com/intel/oap/common/storage/SPDKChunkImpl.java
  oap-common/src/main/java/com/intel/oap/common/storage/SPDKPMemDataStoreImpl.java
  oap-common/src/main/java/com/intel/oap/common/storage/StreamMeta.java
  oap-common/src/main/java/com/intel/oap/common/storage/memkind/MemkindChunkReader.java
  oap-common/src/main/java/com/intel/oap/common/storage/memkind/MemkindChunkWriter.java
  oap-common/src/main/java/com/intel/oap/common/storage/memkind/MemkindMetaStore.java
  oap-common/src/main/java/com/intel/oap/common/storage/stream/ChunkInputStream.java
  oap-common/src/main/java/com/intel/oap/common/storage/stream/ChunkOutputStream.java
  oap-common/src/main/java/com/intel/oap/common/storage/stream/ChunkReader.java
  oap-common/src/main/java/com/intel/oap/common/storage/stream/ChunkWriter.java
  oap-common/src/main/java/com/intel/oap/common/storage/stream/DataStore.java
  oap-common/src/main/java/com/intel/oap/common/storage/stream/MemoryStats.java
  oap-common/src/main/java/com/intel/oap/common/storage/stream/MetaData.java
  oap-common/src/main/java/com/intel/oap/common/storage/stream/PMemID.java
  oap-common/src/main/java/com/intel/oap/common/storage/stream/PMemManager.java
  oap-common/src/main/java/com/intel/oap/common/storage/stream/PMemMetaStore.java
  oap-common/src/main/java/com/intel/oap/common/storage/stream/StoreType.java
  oap-common/src/test/java/com/intel/oap/common/storage/ChunkStreamAPITest.java
  oap-common/src/test/java/com/intel/oap/common/storage/FileChunkTest.java
Labels: ElasticDataFusion

#1301 [oap-native-sql][Scala] Adding upper support
  oap-native-sql/core/src/main/scala/com/intel/sparkColumnarPlugin/expression/ColumnarUnaryOperator.scala
Labels: NativeSQL

#1294 [oap-native-sql][CI] update travis for native sql
  .travis.yml
Labels: NativeSQL

#1308 [oap-native-sql][Doc] update readme
  oap-native-sql/README.md
  oap-native-sql/resource/Native_SQL_Engine_Intro.jpg
  oap-native-sql/resource/core_arch.jpg
Labels: NativeSQL

#1307 [oap-native-sql][Scala]adding if support
  oap-native-sql/core/src/main/scala/com/intel/sparkColumnarPlugin/expression/ColumnarExpressionConverter.scala
  oap-native-sql/core/src/main/scala/com/intel/sparkColumnarPlugin/expression/ColumnarIfOperator.scala
  oap-native-sql/core/src/main/scala/com/intel/sparkColumnarPlugin/expression/ColumnarLiterals.scala
Labels: NativeSQL

#1261 [oap-native-sql] Enable ColumnarSort kernel with code generation
  oap-native-sql/core/src/main/scala/com/intel/sparkColumnarPlugin/ColumnarPlugin.scala
  oap-native-sql/core/src/main/scala/com/intel/sparkColumnarPlugin/ColumnarPluginConfig.scala
  oap-native-sql/core/src/main/scala/com/intel/sparkColumnarPlugin/execution/ColumnarSortExec.scala
  oap-native-sql/core/src/main/scala/com/intel/sparkColumnarPlugin/execution/RowToArrowColumnarExec.scala
  oap-native-sql/core/src/main/scala/com/intel/sparkColumnarPlugin/expression/ColumnarSorter.scala
  oap-native-sql/cpp/src/CMakeLists.txt
  oap-native-sql/cpp/src/benchmarks/CMakeLists.txt
  oap-native-sql/cpp/src/benchmarks/arrow_compute_benchmark_sort.cc
  oap-native-sql/cpp/src/codegen/arrow_compute/code_generator.h
  oap-native-sql/cpp/src/codegen/arrow_compute/expr_visitor.cc
  oap-native-sql/cpp/src/codegen/arrow_compute/expr_visitor_impl.h
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/array_item_index.h
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/code_generator_base.h
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/codegen_common.cc
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/codegen_common.h
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/kernels_ext.cc
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/kernels_ext.h
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/sort_kernel.cc
  oap-native-sql/cpp/src/tests/CMakeLists.txt
  oap-native-sql/cpp/src/tests/arrow_compute_test_sort.cc
Labels: NativeSQL

#1303 [oap-native-sql][Scala]date32 in IN expression
  oap-native-sql/core/src/main/scala/com/intel/sparkColumnarPlugin/expression/ColumnarInOperator.scala
Labels: NativeSQL

#1321 POAE7-307 Rename PMemID to meaningful name
  oap-common/src/main/java/com/intel/oap/common/storage/memkind/MemkindChunkReader.java
  oap-common/src/main/java/com/intel/oap/common/storage/memkind/MemkindChunkWriter.java
  oap-common/src/main/java/com/intel/oap/common/storage/memkind/MemkindMetaStore.java
  oap-common/src/main/java/com/intel/oap/common/storage/memkind/MemkindPMemID.java
  oap-common/src/main/java/com/intel/oap/common/storage/memkind/MemkindPMemPhysicalAddress.java
  oap-common/src/main/java/com/intel/oap/common/storage/stream/ChunkReader.java
  oap-common/src/main/java/com/intel/oap/common/storage/stream/ChunkWriter.java
  oap-common/src/main/java/com/intel/oap/common/storage/stream/PMemID.java
  oap-common/src/main/java/com/intel/oap/common/storage/stream/PMemMetaStore.java
  oap-common/src/main/java/com/intel/oap/common/storage/stream/PMemPhysicalAddress.java
Labels: ElasticDataFusion

#1317 [OAP-Cache-OAP][POAE7-305] Add external cache enable config
  oap-cache/oap/src/main/scala/org/apache/spark/sql/execution/datasources/oap/filecache/OapCache.scala
  oap-cache/oap/src/main/scala/org/apache/spark/sql/internal/oap/OapConf.scala
Labels: Oap Cache
