Repository Intel-bigdata/OAP, pull requests merged in 2020-10, with the labels that each got.

#1775 [OAP-1776][oap-native-sql]fix sort memleak
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/kernels_ext.cc
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/sort_kernel.cc
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/window_sort_kernel.h
Labels: NativeSQL

#1781 [OAP-1765][oap-native-sql] fix codegen for SMJ and HashAgg
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/codegen_common.cc
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/hash_aggregate_kernel.cc
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/merge_join_kernel.cc
Labels: NativeSQL

#1772 [OAP-1771]Update ReadMe for better user experience in oap-data-source installation
  oap-data-source/arrow/README.md
  oap-data-source/arrow/resource/arrowdatasource_validation.png
Labels: OAP 0.9

#1788 [OAP-1765][oap-native-sql] Fix for dropped CoalecseBatches before ColumnarBroadcastExchange
  oap-native-sql/core/src/main/scala/org/apache/spark/sql/execution/adaptive/AdaptiveSparkPlanExec.scala
Labels: NativeSQL

#1467 [OAP-1457][oap-native-sql] Reserve Spark off-heap execution memory after buffer allocation
  .travis.yml
  oap-data-source/arrow/common/pom.xml
  oap-data-source/arrow/common/src/main/scala/org/apache/spark/sql/execution/datasources/v2/arrow/SparkMemoryUtils.scala
  oap-data-source/arrow/common/src/main/scala/org/apache/spark/sql/execution/datasources/v2/arrow/SparkSchemaUtils.scala
  oap-data-source/arrow/parquet/src/test/scala/com/intel/oap/spark/sql/execution/datasources/v2/parquet/ParquetFileFormatTest.scala
  oap-data-source/arrow/pom.xml
  oap-data-source/arrow/standard/pom.xml
  oap-data-source/arrow/standard/src/main/scala/com/intel/oap/spark/sql/execution/datasources/arrow/ArrowFileFormat.scala
  oap-data-source/arrow/standard/src/main/scala/com/intel/oap/spark/sql/execution/datasources/v2/arrow/ArrowPartitionReaderFactory.scala
  oap-data-source/arrow/standard/src/main/scala/com/intel/oap/spark/sql/execution/datasources/v2/arrow/ArrowTable.scala
  oap-data-source/arrow/standard/src/main/scala/com/intel/oap/spark/sql/execution/datasources/v2/arrow/ArrowUtils.scala
  oap-data-source/arrow/standard/src/main/scala/com/intel/oap/spark/sql/execution/datasources/v2/arrow/ExecutionMemoryAllocationListener.scala
  oap-data-source/arrow/standard/src/test/scala/com/intel/oap/spark/sql/execution/datasources/arrow/ArrowDataSourceTPCHBasedTest.scala
  oap-data-source/arrow/standard/src/test/scala/com/intel/oap/spark/sql/execution/datasources/arrow/ArrowDataSourceTest.scala
  oap-native-sql/core/pom.xml
  oap-native-sql/core/src/main/java/com/intel/oap/datasource/VectorizedParquetArrowReader.java
  oap-native-sql/core/src/main/java/com/intel/oap/expression/ColumnarArithmeticWithGandiva.java
  oap-native-sql/core/src/main/java/com/intel/oap/vectorized/AdaptorReferenceManager.java
  oap-native-sql/core/src/main/java/com/intel/oap/vectorized/ArrowRecordBatchBuilderImpl.java
  oap-native-sql/core/src/main/java/com/intel/oap/vectorized/ArrowWritableColumnVector.java
  oap-native-sql/core/src/main/scala/com/intel/oap/execution/CoalesceBatchesExec.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/execution/ColumnarBasicPhysicalOperators.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/execution/ColumnarBroadcastHashJoinExec.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/execution/ColumnarDataSourceRDD.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/execution/ColumnarExpandExec.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/execution/ColumnarHashAggregateExec.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/execution/ColumnarShuffledHashJoinExec.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/execution/ColumnarSortExec.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/execution/ColumnarSortMergeJoinExec.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/execution/ColumnarWholeStageCodegenExec.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/expression/ColumnarConditionProjector.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/expression/ColumnarFilter.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/expression/ConverterUtils.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/vectorized/ArrowColumnarBatchSerializer.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/vectorized/CloseableColumnBatchIterator.scala
  oap-native-sql/core/src/main/scala/org/apache/spark/sql/execution/ColumnarShuffleExchangeExec.scala
  oap-native-sql/core/src/main/scala/org/apache/spark/sql/util/ArrowUtils.scala
Labels: NativeSQL

#1810 [OAP-1771]Fix README for Arrow Data Source
  oap-data-source/arrow/README.md
  oap-data-source/arrow/resource/arrowdatasource_validation.png
Labels: OAP 1.0

#1755 [OAP-1754][Intel MLlib] Improve LibLoader creating temp dir name with UUID
  oap-mllib/mllib-dal/src/main/java/org/apache/spark/ml/util/LibLoader.java
  oap-mllib/mllib-dal/src/main/scala/org/apache/spark/ml/clustering/KMeansDALImpl.scala
Labels: OAP 1.0

#1803 [OAP-1751][oap-native-sql]fix sort on TPC-DS
  oap-native-sql/core/src/main/scala/com/intel/oap/ColumnarPlugin.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/execution/ColumnarSortExec.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/expression/ColumnarSorter.scala
  oap-native-sql/cpp/src/codegen/arrow_compute/expr_visitor.cc
  oap-native-sql/cpp/src/codegen/arrow_compute/expr_visitor_impl.h
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/kernels_ext.h
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/sort_kernel.cc
  oap-native-sql/cpp/src/tests/arrow_compute_test_sort.cc
Labels: NativeSQL

#1830 [OAP-1829][oap-native-sql] Optimize columnar shuffle and option to use AVX-512
  oap-native-sql/core/pom.xml
  oap-native-sql/core/src/main/scala/org/apache/spark/shuffle/ColumnarShuffleWriter.scala
  oap-native-sql/core/src/test/scala/org/apache/spark/sql/RepartitionSuite.scala
  oap-native-sql/core/src/test/scala/org/apache/spark/sql/execution/adaptive/ColumnarAdaptiveQueryExecSuite.scala
  oap-native-sql/cpp/src/CMakeLists.txt
  oap-native-sql/cpp/src/benchmarks/CMakeLists.txt
  oap-native-sql/cpp/src/benchmarks/shuffle_split_benchmark.cc
  oap-native-sql/cpp/src/jni/jni_wrapper.cc
  oap-native-sql/cpp/src/shuffle/partition_writer.cc
  oap-native-sql/cpp/src/shuffle/partition_writer.h
  oap-native-sql/cpp/src/shuffle/splitter.cc
  oap-native-sql/cpp/src/shuffle/splitter.h
  oap-native-sql/cpp/src/shuffle/type.h
  oap-native-sql/cpp/src/shuffle/utils.h
  oap-native-sql/cpp/src/tests/shuffle_split_test.cc
Labels: NativeSQL

#1834 [OAP-1833][oap-native-sql][Scala] fix CoalesceBatchs after HashAgg
  oap-native-sql/core/src/main/scala/org/apache/spark/sql/execution/adaptive/AdaptiveSparkPlanExec.scala
Labels: NativeSQL

#1832 [OAP-1831][oap-native-sql] ColumnarWindow: Support reusing same windo…
  oap-native-sql/core/src/main/scala/com/intel/oap/execution/ColumnarWindowExec.scala
  oap-native-sql/cpp/src/codegen/arrow_compute/expr_visitor.cc
  oap-native-sql/cpp/src/codegen/arrow_compute/expr_visitor.h
  oap-native-sql/cpp/src/codegen/arrow_compute/expr_visitor_impl.h
Labels: NativeSQL

#1845 [OAP-1844][oap-native-sql] Fix columnar shuffle spilled file not deleted
  oap-native-sql/cpp/src/shuffle/splitter.cc
  oap-native-sql/cpp/src/shuffle/splitter.h
  oap-native-sql/cpp/src/shuffle/utils.h
Labels: NativeSQL
