Repository Intel-bigdata/OAP, pull requests merged in 2020-07, with the labels that each got.

#1414 update pmemkv to stable 1.0 version
  dev/install_pmemkv.sh
  oap-cache/oap/pom.xml
  oap-common/pom.xml
  oap-common/src/main/java/com/intel/oap/common/storage/pmemblk/PMemBlkMetaStore.java
  oap-common/src/main/java/com/intel/oap/common/storage/pmemblk/PMemKVDatabase.java
  pom.xml
Labels: ElasticDataFusion

#1312 [oap-native-sql][Scala] adding cast support
  oap-native-sql/core/src/main/scala/com/intel/sparkColumnarPlugin/expression/CodeGeneration.scala
  oap-native-sql/core/src/main/scala/com/intel/sparkColumnarPlugin/expression/ColumnarUnaryOperator.scala
  oap-native-sql/core/src/main/scala/com/intel/sparkColumnarPlugin/expression/ConverterUtils.scala
Labels: NativeSQL

#1401 [oap-native-sql]Wip codegen aggregate
  oap-native-sql/.scalafmt.conf
  oap-native-sql/core/src/main/scala/com/intel/sparkColumnarPlugin/ColumnarPluginConfig.scala
  oap-native-sql/core/src/main/scala/com/intel/sparkColumnarPlugin/execution/ColumnarHashAggregateExec.scala
  oap-native-sql/core/src/main/scala/com/intel/sparkColumnarPlugin/expression/ColumnarCaseWhenOperator.scala
  oap-native-sql/core/src/main/scala/com/intel/sparkColumnarPlugin/expression/ColumnarExpressionConverter.scala
  oap-native-sql/core/src/main/scala/com/intel/sparkColumnarPlugin/expression/ColumnarGroupbyHashAggregation.scala
  oap-native-sql/cpp/src/CMakeLists.txt
  oap-native-sql/cpp/src/benchmarks/CMakeLists.txt
  oap-native-sql/cpp/src/benchmarks/arrow_compute_benchmark.cc
  oap-native-sql/cpp/src/benchmarks/arrow_compute_benchmark_hash_aggregate.cc
  oap-native-sql/cpp/src/codegen/arrow_compute/expr_visitor.cc
  oap-native-sql/cpp/src/codegen/arrow_compute/expr_visitor.h
  oap-native-sql/cpp/src/codegen/arrow_compute/expr_visitor_impl.h
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/action_codegen.h
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/code_generator_base.h
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/codegen_common.cc
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/codegen_common.h
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/codegen_node_visitor.cc
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/codegen_node_visitor.h
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/codegen_register.cc
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/codegen_register.h
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/hash_aggregate_kernel.cc
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/kernels_ext.cc
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/kernels_ext.h
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/probe_kernel.cc
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/typed_action_codegen_impl.h
  oap-native-sql/cpp/src/tests/CMakeLists.txt
  oap-native-sql/cpp/src/tests/arrow_compute_test_hashaggregate.cc
Labels: NativeSQL

#1436 [oap-native-sql]merge nativesql oap 0.9 batch2
  oap-data-source/arrow/src/main/scala/com/intel/oap/spark/sql/execution/datasources/arrow/ArrowFileFormat.scala
  oap-data-source/arrow/src/test/scala/com/intel/oap/spark/sql/execution/datasources/arrow/ArrowDataSourceTest.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/expression/ColumnarGroupbyHashAggregation.scala
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/hash_aggregate_kernel.cc
Labels: NativeSQL

#1400 [OAP-1458][oap-native-sql] adding ExistenceJoin support
  oap-native-sql/core/src/main/scala/com/intel/oap/expression/ColumnarShuffledHashJoin.scala
  oap-native-sql/cpp/src/codegen/arrow_compute/expr_visitor.cc
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/codegen_common.cc
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/probe_kernel.cc
  oap-native-sql/cpp/src/tests/arrow_compute_test_join.cc
Labels: NativeSQL

#1469 [OAP-1468][oap-native-sql][CI] update to depends on oap-0.9 branch
  .travis.yml
Labels: NativeSQL

#1454 [OAP-1452][OAP-MLLIB] Bugfix for Intel MLlib initial release
  oap-mllib/README.md
  oap-mllib/examples/kmeans-hibench/run-hibench-oap-mllib.sh
  oap-mllib/examples/kmeans-hibench/run-hibench-vanilla.sh
  oap-mllib/examples/kmeans-pyspark/run.sh
  oap-mllib/examples/kmeans/run.sh
  oap-mllib/mllib-dal/pom.xml
  oap-mllib/mllib-dal/src/main/java/org/apache/spark/ml/util/LibLoader.java
  oap-mllib/mllib-dal/src/main/native/Makefile
Labels: Intel MLlib

#1463 [OAP-1462][oap-native-sql]Adaptive query execution columnar support
  oap-native-sql/core/src/main/scala/com/intel/oap/ColumnarPlugin.scala
  oap-native-sql/core/src/main/scala/org/apache/spark/shuffle/ColumnarShuffleWriter.scala
  oap-native-sql/core/src/main/scala/org/apache/spark/shuffle/sort/ColumnarShuffleManager.scala
  oap-native-sql/core/src/main/scala/org/apache/spark/sql/execution/ColumnarShuffleExchangeExec.scala
  oap-native-sql/core/src/main/scala/org/apache/spark/sql/execution/ShuffledColumnarBatchRDD.scala
  oap-native-sql/core/src/main/scala/org/apache/spark/sql/execution/adaptive/AdaptiveSparkPlanExec.scala
  oap-native-sql/core/src/main/scala/org/apache/spark/sql/execution/adaptive/ColumnarCustomShuffleReaderExec.scala
  oap-native-sql/core/src/main/scala/org/apache/spark/sql/execution/adaptive/QueryStageExec.scala
  oap-native-sql/core/src/test/scala/org/apache/spark/sql/RepartitionSuite.scala
  oap-native-sql/core/src/test/scala/org/apache/spark/sql/execution/adaptive/ColumnarAdaptiveQueryExecSuite.scala
  oap-native-sql/cpp/src/shuffle/partition_writer.cc
  oap-native-sql/cpp/src/shuffle/partition_writer.h
  oap-native-sql/cpp/src/shuffle/splitter.cc
  oap-native-sql/cpp/src/shuffle/splitter.h
Labels: NativeSQL

#1456 [OAP-1455][OAP-cache][POAE7-334]Remove unnecessary memcopy in plasma code path
  oap-cache/oap/src/main/scala/org/apache/spark/sql/execution/datasources/oap/filecache/FiberCacheManager.scala
  oap-cache/oap/src/main/scala/org/apache/spark/sql/execution/datasources/oap/filecache/FiberId.scala
  oap-cache/oap/src/main/scala/org/apache/spark/sql/execution/datasources/oap/filecache/MemoryManager.scala
  oap-cache/oap/src/main/scala/org/apache/spark/sql/execution/datasources/oap/filecache/OapCache.scala
  oap-cache/oap/src/main/scala/org/apache/spark/sql/execution/datasources/oap/io/DataFile.scala
  oap-cache/oap/src/main/scala/org/apache/spark/sql/execution/datasources/oap/io/OapDataFile.scala
  oap-cache/oap/src/main/scala/org/apache/spark/sql/execution/datasources/oap/io/OrcDataFile.scala
  oap-cache/oap/src/main/scala/org/apache/spark/sql/execution/datasources/oap/io/ParquetDataFiberCompressedReaderWriter.scala
  oap-cache/oap/src/main/scala/org/apache/spark/sql/execution/datasources/oap/io/ParquetDataFiberReaderWriter.scala
  oap-cache/oap/src/main/scala/org/apache/spark/sql/execution/datasources/oap/io/ParquetDataFile.scala
  oap-cache/oap/src/main/scala/org/apache/spark/sql/execution/datasources/oap/io/ParquetFiberDataLoader.scala
  oap-cache/oap/src/test/scala/org/apache/spark/sql/execution/datasources/oap/io/ParquetDataFileSuite.scala
  oap-cache/oap/src/test/scala/org/apache/spark/sql/execution/datasources/oap/io/TestDataFile.scala
Labels: ElasticDataFusion

#1470 [OAP-1471] [OAP-MLlib] Package all oneCCL libs into jar and change related loading logics
  oap-mllib/README.md
  oap-mllib/examples/kmeans-hibench/build.sh
  oap-mllib/examples/kmeans-hibench/run-hibench-oap-mllib.sh
  oap-mllib/examples/kmeans-hibench/run-hibench-vanilla.sh
  oap-mllib/examples/kmeans-pyspark/run.sh
  oap-mllib/examples/kmeans/run.sh
  oap-mllib/mllib-dal/build.sh
  oap-mllib/mllib-dal/src/assembly/assembly.xml
  oap-mllib/mllib-dal/src/main/java/org/apache/spark/ml/util/LibLoader.java
  oap-mllib/mllib-dal/src/main/native/Makefile
  oap-mllib/mllib-dal/src/main/scala/org/apache/spark/ml/util/OneCCL.scala
Labels: Intel MLlib

#1497 [OAP-1477][oap-native-sql] Remove redundant 'total' in metrics
  oap-native-sql/core/src/main/scala/com/intel/oap/execution/CoalesceBatchesExec.scala
Labels: NativeSQL

#1490 [oap-native-sql]Accelerate codegen compilation
  oap-native-sql/core/src/main/java/com/intel/oap/vectorized/ExpressionEvaluator.java
  oap-native-sql/core/src/main/java/com/intel/oap/vectorized/ExpressionEvaluatorJniWrapper.java
  oap-native-sql/core/src/main/java/com/intel/oap/vectorized/JniUtils.java
  oap-native-sql/core/src/main/scala/com/intel/oap/ColumnarPlugin.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/ColumnarPluginConfig.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/execution/ColumnarHashAggregateExec.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/execution/ColumnarShuffledHashJoinExec.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/execution/ColumnarSortExec.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/expression/ColumnarGroupbyHashAggregation.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/expression/ColumnarShuffledHashJoin.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/expression/ColumnarSorter.scala
  oap-native-sql/core/src/main/scala/org/apache/spark/sql/execution/ColumnarShuffleExchangeExec.scala
  oap-native-sql/core/src/main/scala/org/apache/spark/util/UserAddedJarUtils.scala
  oap-native-sql/cpp/src/CMakeLists.txt
  oap-native-sql/cpp/src/benchmarks/arrow_compute_benchmark_sort.cc
  oap-native-sql/cpp/src/codegen/arrow_compute/code_generator.h
  oap-native-sql/cpp/src/codegen/arrow_compute/expr_visitor.h
  oap-native-sql/cpp/src/codegen/arrow_compute/expr_visitor_impl.h
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/action_codegen.h
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/code_generator_base.h
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/codegen_common.cc
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/codegen_common.h
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/hash_aggregate_kernel.cc
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/kernels_ext.cc
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/kernels_ext.h
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/probe_kernel.cc
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/sort_kernel.cc
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/typed_action_codegen_impl.h
  oap-native-sql/cpp/src/codegen/code_generator.h
  oap-native-sql/cpp/src/codegen/common/result_iterator.h
  oap-native-sql/cpp/src/jni/jni_common.h
  oap-native-sql/cpp/src/jni/jni_wrapper.cc
  oap-native-sql/cpp/src/precompile/array.cc
  oap-native-sql/cpp/src/precompile/array.h
  oap-native-sql/cpp/src/precompile/builder.cc
  oap-native-sql/cpp/src/precompile/builder.h
  oap-native-sql/cpp/src/precompile/hash_arrays_kernel.cc
  oap-native-sql/cpp/src/precompile/hash_arrays_kernel.h
  oap-native-sql/cpp/src/precompile/hash_map.cc
  oap-native-sql/cpp/src/precompile/hash_map.h
  oap-native-sql/cpp/src/precompile/sort.cc
  oap-native-sql/cpp/src/precompile/sort.h
  oap-native-sql/cpp/src/precompile/sparse_hash_map.cc
  oap-native-sql/cpp/src/precompile/sparse_hash_map.h
  oap-native-sql/cpp/src/precompile/type.cc
  oap-native-sql/cpp/src/precompile/type.h
  oap-native-sql/cpp/src/precompile/vector.cc
  oap-native-sql/cpp/src/precompile/vector.h
  oap-native-sql/cpp/src/tests/CMakeLists.txt
  oap-native-sql/cpp/src/tests/arrow_compute_test_precompile.cc
  oap-native-sql/cpp/src/third_party/arrow/utils/hashing.h
  oap-native-sql/cpp/src/third_party/sparsehash/sparse_hash_map.h
Labels: NativeSQL

#1504 [OAP-1508][oap-native-sql] Clean java tmp dir when doing compilation
  oap-native-sql/core/src/main/java/com/intel/oap/vectorized/ExpressionEvaluator.java
  oap-native-sql/core/src/main/java/com/intel/oap/vectorized/ExpressionEvaluatorJniWrapper.java
  oap-native-sql/core/src/main/java/com/intel/oap/vectorized/JniUtils.java
  oap-native-sql/core/src/main/scala/com/intel/oap/ColumnarPluginConfig.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/execution/ColumnarHashAggregateExec.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/execution/ColumnarShuffledHashJoinExec.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/execution/ColumnarSortExec.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/expression/ColumnarShuffledHashJoin.scala
  oap-native-sql/cpp/src/jni/jni_wrapper.cc
Labels: NativeSQL

#1509 [OAP-1510][oap-nativel-sql][Doc] refine nativel sql installation doc
  oap-native-sql/README.md
  oap-native-sql/resource/installation.md
Labels: NativeSQL

#1518 [OAP-1510][oap-nativel-sql][Doc] refine nativel sql testing doc
  README.md
  oap-native-sql/README.md
  oap-native-sql/resource/installation.md
Labels: NativeSQL

#1524 [OAP-1523][oap-native-sql]clean up metric
  oap-native-sql/core/src/main/scala/com/intel/oap/execution/ColumnarBasicPhysicalOperators.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/execution/ColumnarBatchScanExec.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/execution/ColumnarHashAggregateExec.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/execution/ColumnarShuffledHashJoinExec.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/execution/ColumnarSortExec.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/execution/RowToArrowColumnarExec.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/expression/ColumnarAggregation.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/expression/ColumnarConditionProjector.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/expression/ColumnarGroupbyHashAggregation.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/expression/ColumnarShuffledHashJoin.scala
Labels: NativeSQL

#1552 [OAP-1551] [OAP-MLlib] Temp remove CI for MLlib
  .travis.yml
Labels: Intel MLlib, OAP 0.9

#1546 [OAP-1547][oap-native-sql][Scala] Adding metrics for input/output batches
  oap-native-sql/core/src/main/scala/com/intel/oap/execution/CoalesceBatchesExec.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/execution/ColumnarBasicPhysicalOperators.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/execution/ColumnarBatchScanExec.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/execution/ColumnarDataSourceRDD.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/execution/ColumnarHashAggregateExec.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/execution/ColumnarSortExec.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/execution/RowToArrowColumnarExec.scala
Labels: NativeSQL
