Repository Intel-bigdata/OAP, pull requests merged in 2020-08, with the labels that each got.

#1563 [OAP-1562][OAP-MLlib] Fix CI for oneapi beta07
  .travis.yml
  oap-mllib/dev/install-build-deps-bionic.sh
  oap-mllib/dev/install-build-deps-centos.sh
Labels: Intel MLlib, OAP 0.9

#1575 [OAP-MLlib] kmeans-hibench default init to Random, remove daal from example pom
  oap-mllib/examples/kmeans-hibench/pom.xml
  oap-mllib/examples/kmeans-hibench/src/main/scala/com/intel/hibench/sparkbench/ml/DenseKMeansDS.scala
  oap-mllib/examples/kmeans/pom.xml
Labels: OAP 0.9

#1578 [SQL Index and Data Source Cache] [OAP-1557] [OAP-1525] Update doc for Plasma
  oap-cache/oap/docs/User-Guide.md
Labels: OAP 0.8, OAP 0.9

#1596 [OAP-MLlib] Clean up POM to remove unnecessaries for examples and mllib-dal
  oap-mllib/examples/kmeans-hibench/pom.xml
  oap-mllib/examples/kmeans/pom.xml
  oap-mllib/mllib-dal/pom.xml
Labels: Intel MLlib, OAP 0.9

#1597 [SQL Data Source Cache][POAE7-152] Consistent hash based scheduler
  oap-cache/oap/src/main/scala/org/apache/spark/sql/internal/oap/OapConf.scala
  oap-cache/oap/src/main/spark3.0.0/scala/org/apache/spark/sql/execution/datasources/FilePartition.scala
  oap-cache/oap/src/test/scala/org/apache/spark/sql/execution/datasources/oap/filecache/TaskLocationSuite.scala
Labels: OAP 0.9

#1611 [OAP-MLlib] fix repartition bug for not enough partitions
  oap-mllib/mllib-dal/src/main/scala/org/apache/spark/ml/clustering/KMeansDALImpl.scala
Labels: OAP 0.9

#1600 [oap-native-sql][Scala] fix broadcasthashjoin
  oap-native-sql/core/src/main/scala/com/intel/oap/expression/ColumnarShuffledHashJoin.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/expression/ConverterUtils.scala
Labels: NativeSQL

#1501 [OAP-1517] [oap-native-sql]Implement SortMergeJoin Part1
  oap-native-sql/core/src/main/scala/com/intel/oap/ColumnarPlugin.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/ColumnarPluginConfig.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/execution/ColumnarSortMergeJoinExec.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/expression/ColumnarSortMergeJoin.scala
  oap-native-sql/cpp/src/CMakeLists.txt
  oap-native-sql/cpp/src/codegen/arrow_compute/expr_visitor.cc
  oap-native-sql/cpp/src/codegen/arrow_compute/expr_visitor_impl.h
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/codegen_common.cc
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/kernels_ext.h
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/merge_join_kernel.cc
  oap-native-sql/cpp/src/tests/CMakeLists.txt
  oap-native-sql/cpp/src/tests/arrow_compute_test_join_smj.cc
Labels: NativeSQL

#1593 [OAP-1558][oap-native-sql] TPC-H bitwise operators: BitwiseAnd, Bitwi…
  oap-native-sql/core/src/main/scala/com/intel/oap/expression/ColumnarArithmetic.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/expression/ColumnarUnaryOperator.scala
Labels: NativeSQL

#1594 [OAP-1498][oap-native-sql] adding support for stddev_samp without codegen
  oap-native-sql/core/src/main/scala/com/intel/oap/expression/ColumnarAggregateExpression.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/expression/ColumnarAggregation.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/expression/ColumnarExpressionConverter.scala
  oap-native-sql/cpp/src/codegen/arrow_compute/expr_visitor.cc
  oap-native-sql/cpp/src/codegen/arrow_compute/expr_visitor_impl.h
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/actions_impl.h
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/kernels_ext.cc
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/kernels_ext.h
  oap-native-sql/cpp/src/tests/arrow_compute_test_aggregate.cc
Labels: NativeSQL

#1586 [OAP-1587][oap-native-sql] tpcds enabling (part1)
  oap-native-sql/core/src/main/java/com/intel/oap/vectorized/ArrowWritableColumnVector.java
  oap-native-sql/core/src/main/scala/com/intel/oap/ColumnarPlugin.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/ColumnarPluginConfig.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/execution/ColumnarBroadcastHashJoinExec.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/execution/ColumnarHashAggregateExec.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/execution/ColumnarShuffledHashJoinExec.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/execution/RowToArrowColumnarExec.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/expression/ColumnarAggregateExpression.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/expression/ColumnarAggregation.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/expression/ColumnarCaseWhenOperator.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/expression/ColumnarExpressionConverter.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/expression/ColumnarGroupbyHashAggregation.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/expression/ColumnarProjection.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/expression/ColumnarShuffledHashJoin.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/expression/ColumnarSorter.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/expression/ColumnarUnaryOperator.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/expression/ConverterUtils.scala
  oap-native-sql/cpp/src/codegen/arrow_compute/expr_visitor.cc
  oap-native-sql/cpp/src/codegen/arrow_compute/expr_visitor_impl.h
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/action_codegen.h
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/codegen_common.cc
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/codegen_common.h
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/hash_aggregate_kernel.cc
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/kernels_ext.cc
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/probe_kernel.cc
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/typed_action_codegen_impl.h
  oap-native-sql/cpp/src/precompile/hash_arrays_kernel.cc
  oap-native-sql/cpp/src/tests/arrow_compute_test_hashaggregate.cc
Labels: NativeSQL

#1639 [OAP-1638][oap-native-sql] tpcds enabling (part2)
  oap-native-sql/core/src/main/java/com/intel/oap/vectorized/ArrowWritableColumnVector.java
  oap-native-sql/core/src/main/scala/com/intel/oap/execution/ColumnarBroadcastHashJoinExec.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/expression/ColumnarConditionProjector.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/expression/ColumnarExpressionConverter.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/expression/ConverterUtils.scala
  oap-native-sql/cpp/src/CMakeLists.txt
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/action_codegen.h
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/codegen_common.h
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/codegen_node_visitor.cc
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/codegen_node_visitor.h
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/hash_aggregate_kernel.cc
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/merge_join_kernel.cc
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/probe_kernel.cc
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/typed_action_codegen_impl.h
  oap-native-sql/cpp/src/tests/CMakeLists.txt
  oap-native-sql/cpp/src/tests/arrow_compute_test_check_condition.cc
  oap-native-sql/cpp/src/tests/arrow_compute_test_hashaggregate.cc
Labels: NativeSQL

#1648 [OAP-1482][oap-native-sql] Columnar shuffle decimal support
  oap-native-sql/cpp/src/shuffle/partition_writer.h
  oap-native-sql/cpp/src/shuffle/splitter.cc
  oap-native-sql/cpp/src/shuffle/type.h
  oap-native-sql/cpp/src/shuffle/utils.h
  oap-native-sql/cpp/src/tests/shuffle_split_test.cc
Labels: NativeSQL

#1649 [OAP-1647][oap-native-sql] row to columnar for decimal
  oap-native-sql/core/src/main/java/com/intel/oap/vectorized/ArrowWritableColumnVector.java
  oap-native-sql/core/src/main/scala/com/intel/oap/execution/RowToArrowColumnarExec.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/expression/ColumnarUnaryOperator.scala
Labels: NativeSQL

#1603 [OAP-1602][oap-native-sql][Java] fix exract resource from jar
  oap-native-sql/core/src/main/java/com/intel/oap/vectorized/JniUtils.java
Labels: NativeSQL

#1601 [OAP-1602][oap-native-sql][Java] fix exract resource from jar
  oap-native-sql/core/src/main/java/com/intel/oap/vectorized/JniUtils.java
Labels: NativeSQL

#1630 [OAP-1629][oap-native-sql] clean up building scripts
  oap-native-sql/core/pom.xml
  oap-native-sql/cpp/src/CMakeLists.txt
Labels: NativeSQL

#1655 [OAP-1654][oap-native-sql]Columnar shuffle tpcds enabling
  oap-native-sql/core/src/main/scala/com/intel/oap/execution/CoalesceBatchesExec.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/vectorized/ArrowColumnarBatchSerializer.scala
  oap-native-sql/core/src/main/scala/org/apache/spark/shuffle/ColumnarShuffleDependency.scala
  oap-native-sql/core/src/main/scala/org/apache/spark/shuffle/ColumnarShuffleWriter.scala
  oap-native-sql/core/src/main/scala/org/apache/spark/sql/execution/ColumnarShuffleExchangeExec.scala
  oap-native-sql/core/src/test/resources/test-data/native-splitter-output-all-null
  oap-native-sql/core/src/test/resources/test-data/native-splitter-output-nullable-string
  oap-native-sql/core/src/test/resources/test-data/part-00000-d648dd34-c9d2-4fe9-87f2-770ef3551442-c000.snappy.parquet
  oap-native-sql/core/src/test/scala/com/intel/oap/vectorized/ArrowColumnarBatchSerializerSuite.scala
  oap-native-sql/core/src/test/scala/org/apache/spark/shuffle/ColumnarShuffleWriterSuite.scala
  oap-native-sql/core/src/test/scala/org/apache/spark/sql/RepartitionSuite.scala
  oap-native-sql/cpp/src/jni/jni_common.h
  oap-native-sql/cpp/src/jni/jni_wrapper.cc
  oap-native-sql/cpp/src/shuffle/partition_writer.cc
  oap-native-sql/cpp/src/shuffle/partition_writer.h
  oap-native-sql/cpp/src/shuffle/splitter.cc
  oap-native-sql/cpp/src/tests/shuffle_split_test.cc
Labels: NativeSQL

#1664 [OAP-MLlib] Add platform compatibility check
  oap-mllib/mllib-dal/src/main/java/org/apache/spark/ml/util/LibLoader.java
  oap-mllib/mllib-dal/src/main/native/OneDAL.cpp
  oap-mllib/mllib-dal/src/main/native/javah/org_apache_spark_ml_util_OneDAL__.h
  oap-mllib/mllib-dal/src/main/scala/org/apache/spark/ml/clustering/KMeans.scala
  oap-mllib/mllib-dal/src/main/scala/org/apache/spark/ml/util/OneDAL.scala
  oap-mllib/mllib-dal/src/main/scala/org/apache/spark/ml/util/Utils.scala
Labels: OAP 0.9
