Repository Intel-bigdata/OAP, pull requests merged in 2020-12, with the labels that each got.

#1970 [OAP-1947][oap-native-sql][C++] reduce sort kernel memory footprint
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/array_item_index.h
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/sort_kernel.cc
Labels: OAP 1.0

#1976 [OAP-1983][oap-native-sql] Fix hashCheck performance issue
  oap-native-sql/core/src/main/scala/org/apache/spark/sql/execution/ColumnarHashedRelation.scala
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/codegen_context.h
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/conditioned_probe_kernel.cc
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/hash_relation_kernel.cc
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/whole_stage_codegen_kernel.cc
  oap-native-sql/cpp/src/codegen/common/hash_relation.h
  oap-native-sql/cpp/src/precompile/unsafe_array.h
  oap-native-sql/cpp/src/third_party/row_wise_memory/hashMap.h
  oap-native-sql/cpp/src/third_party/row_wise_memory/unsafe_row.h
Labels: OAP 1.0, needsbackport

#1988 [OAP-1983][oap-native-sql] Fix Q38 and Q87 when unsafeRow contains null
  oap-native-sql/cpp/src/third_party/row_wise_memory/unsafe_row.h
Labels: OAP 1.0, needsbackport

#1994 [OAP-1999][oap-native-sql]backport master PR1976 and PR1988
  oap-native-sql/core/src/main/scala/org/apache/spark/sql/execution/ColumnarHashedRelation.scala
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/codegen_context.h
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/conditioned_probe_kernel.cc
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/hash_relation_kernel.cc
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/whole_stage_codegen_kernel.cc
  oap-native-sql/cpp/src/codegen/common/hash_relation.h
  oap-native-sql/cpp/src/precompile/unsafe_array.h
  oap-native-sql/cpp/src/third_party/row_wise_memory/hashMap.h
  oap-native-sql/cpp/src/third_party/row_wise_memory/unsafe_row.h
Labels: NativeSQL, backport

#1993 [OAP-1992][oap-native-sql] suppress warnings
  oap-native-sql/core/src/main/java/com/intel/oap/vectorized/JniUtils.java
  oap-native-sql/core/src/main/scala/com/intel/oap/expression/ColumnarAggregation.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/expression/ColumnarConditionProjector.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/expression/ColumnarGroupbyHashAggregation.scala
Labels: NativeSQL

#1996 [OAP-1998][oap-native-sql] Add support to do numa binding for Columnar Operations
  oap-native-sql/core/src/main/scala/com/intel/oap/ColumnarPluginConfig.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/execution/ColumnarBasicPhysicalOperators.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/execution/ColumnarBroadcastHashJoinExec.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/execution/ColumnarDataSourceRDD.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/execution/ColumnarHashAggregateExec.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/execution/ColumnarShuffledHashJoinExec.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/execution/ColumnarSortExec.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/execution/ColumnarWholeStageCodegenExec.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/execution/ColumnarWindowExec.scala
  oap-native-sql/core/src/main/scala/org/apache/spark/util/ExecutorManager.scala
Labels: NativeSQL, needsbackport

#2005 [OAP-1992][oap-native-sql] remove error type
  oap-native-sql/core/src/main/scala/com/intel/oap/expression/ColumnarConditionProjector.scala
Labels: NativeSQL

#2011 [OAP-2010][oap-native-sql] Add abs support in wscg
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/expression_codegen_visitor.cc
Labels: NativeSQL

#2009 [oap-native-sql] Add a new folder to store ut and post_process scripts
  oap-native-sql/tools/process.py
  oap-native-sql/tools/run_ut.sh
Labels: NativeSQL

#1931 [OAP-1517][oap-native-sql]Columnar SMJ: improvement on SortMergeJoin
  oap-native-sql/core/src/main/scala/com/intel/oap/ColumnarPlugin.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/execution/ColumnarSortMergeJoinExec.scala
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/merge_join_kernel.cc
Labels: NativeSQL

#2024 [OAP-2023] [OAP-MLlib] Switch to oneAPI 2021.1.1 official release and oneCCL beta 08
  oap-mllib/dev/install-build-deps-centos.sh
  oap-mllib/dev/install-build-deps-ubuntu.sh
  oap-mllib/mllib-dal/pom.xml
Labels: OAP 1.0, feature

#2038 [OAP-1999][oap-native-sql]Backport patches to 1.0 branch
  oap-native-sql/core/src/main/scala/com/intel/oap/ColumnarPluginConfig.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/execution/ColumnarBasicPhysicalOperators.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/execution/ColumnarBroadcastHashJoinExec.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/execution/ColumnarDataSourceRDD.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/execution/ColumnarHashAggregateExec.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/execution/ColumnarShuffledHashJoinExec.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/execution/ColumnarSortExec.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/execution/ColumnarWholeStageCodegenExec.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/execution/ColumnarWindowExec.scala
  oap-native-sql/core/src/main/scala/org/apache/spark/util/ExecutorManager.scala
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/expression_codegen_visitor.cc
Labels: NativeSQL, OAP 1.0, backport

#2002 [OAP-2001][oap-native-sql]fix coding style
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/basic_physical_kernels.cc
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/codegen_common.cc
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/conditioned_probe_kernel.cc
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/hash_aggregate_kernel.cc
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/kernels_ext.cc
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/kernels_ext.h
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/merge_join_kernel.cc
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/probe_kernel.cc
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/sort_kernel.cc
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/whole_stage_codegen_kernel.cc
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/window_sort_kernel.h
  oap-native-sql/cpp/src/codegen/code_generator.h
  oap-native-sql/cpp/src/tests/arrow_compute_test_join_smj.cc
  oap-native-sql/cpp/src/tests/arrow_compute_test_join_wocg.cc
  oap-native-sql/cpp/src/tests/arrow_compute_test_wscg.cc
  oap-native-sql/cpp/src/third_party/datetime/date.h
  oap-native-sql/cpp/src/third_party/row_wise_memory/hashMap.h
  oap-native-sql/cpp/src/third_party/row_wise_memory/unsafe_row.h
Labels: NativeSQL, OAP 1.0

#1928 [OAP-1892][oap-native-sql] Optional cache spilled data in memory
  oap-native-sql/core/src/main/java/com/intel/oap/vectorized/ShuffleSplitterJniWrapper.java
  oap-native-sql/core/src/main/java/com/intel/oap/vectorized/SplitResult.java
  oap-native-sql/core/src/main/scala/com/intel/oap/ColumnarPluginConfig.scala
  oap-native-sql/core/src/main/scala/org/apache/spark/shuffle/ColumnarShuffleDependency.scala
  oap-native-sql/core/src/main/scala/org/apache/spark/shuffle/ColumnarShuffleWriter.scala
  oap-native-sql/core/src/main/scala/org/apache/spark/shuffle/sort/ColumnarShuffleManager.scala
  oap-native-sql/core/src/main/scala/org/apache/spark/sql/execution/ColumnarShuffleExchangeExec.scala
  oap-native-sql/core/src/test/scala/org/apache/spark/shuffle/ColumnarShuffleWriterSuite.scala
  oap-native-sql/cpp/src/benchmarks/shuffle_split_benchmark.cc
  oap-native-sql/cpp/src/jni/jni_wrapper.cc
  oap-native-sql/cpp/src/shuffle/splitter.cc
  oap-native-sql/cpp/src/shuffle/splitter.h
  oap-native-sql/cpp/src/shuffle/type.h
  oap-native-sql/cpp/src/shuffle/utils.h
  oap-native-sql/cpp/src/tests/shuffle_split_test.cc
Labels: NativeSQL

#2039 [OAP-2023][OAP-MLlib] Switch to oneAPI 2021.1.1 official release for OAP 1.0
  .travis.yml
  dev/compile-oap.sh
  oap-mllib/dev/install-build-deps-centos.sh
  oap-mllib/dev/install-build-deps-ubuntu.sh
  oap-mllib/mllib-dal/pom.xml
  oap-mllib/mllib-dal/src/assembly/assembly.xml
  oap-mllib/mllib-dal/src/main/java/org/apache/spark/ml/util/LibLoader.java
Labels: OAP 1.0, feature

#2042 [OAP-2041][oap-native-sql] skip null checking if allowed
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/merge_join_kernel.cc
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/probe_kernel.cc
Labels: NativeSQL

#1891 [OAP-1852][oap-native-sql] Memory Management: Pass Spark managed memory pool to code generators
  oap-data-source/arrow/common/src/main/scala/org/apache/spark/sql/execution/datasources/v2/arrow/SparkMemoryUtils.scala
  oap-data-source/arrow/parquet/src/test/scala/com/intel/oap/spark/sql/execution/datasources/v2/parquet/ParquetFileFormatTest.scala
  oap-data-source/arrow/standard/src/main/scala/com/intel/oap/spark/sql/execution/datasources/v2/arrow/ArrowUtils.scala
  oap-data-source/arrow/standard/src/test/scala/com/intel/oap/spark/sql/execution/datasources/arrow/ArrowDataSourceTPCHBasedTest.scala
  oap-data-source/arrow/standard/src/test/scala/com/intel/oap/spark/sql/execution/datasources/arrow/ArrowDataSourceTest.scala
  oap-native-sql/core/src/main/java/com/intel/oap/expression/ColumnarArithmeticWithGandiva.java
  oap-native-sql/core/src/main/java/com/intel/oap/vectorized/ArrowRecordBatchBuilderImpl.java
  oap-native-sql/core/src/main/java/com/intel/oap/vectorized/ArrowWritableColumnVector.java
  oap-native-sql/core/src/main/java/com/intel/oap/vectorized/ExpressionEvaluator.java
  oap-native-sql/core/src/main/java/com/intel/oap/vectorized/ExpressionEvaluatorJniWrapper.java
  oap-native-sql/core/src/main/java/com/intel/oap/vectorized/ExpressionMemoryPool.java
  oap-native-sql/core/src/main/java/com/intel/oap/vectorized/ShuffleSplitterJniWrapper.java
  oap-native-sql/core/src/main/scala/com/intel/oap/execution/ColumnarWindowExec.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/vectorized/ArrowColumnarBatchSerializer.scala
  oap-native-sql/core/src/main/scala/org/apache/spark/shuffle/ColumnarShuffleWriter.scala
  oap-native-sql/core/src/main/scala/org/apache/spark/sql/execution/ColumnarBroadcastExchangeExec.scala
  oap-native-sql/cpp/src/codegen/arrow_compute/code_generator.h
  oap-native-sql/cpp/src/codegen/arrow_compute/expr_visitor.cc
  oap-native-sql/cpp/src/codegen/arrow_compute/expr_visitor.h
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/window_kernel.cc
  oap-native-sql/cpp/src/codegen/code_generator_factory.h
  oap-native-sql/cpp/src/codegen/common/hash_relation.h
  oap-native-sql/cpp/src/jni/jni_wrapper.cc
  oap-native-sql/cpp/src/shuffle/splitter.cc
  oap-native-sql/cpp/src/third_party/row_wise_memory/hashMap.h
Labels: NativeSQL

#2032 [OAP-1995][oap-native-sql] add NaN support in comparison
  oap-native-sql/core/src/main/scala/com/intel/oap/ColumnarPluginConfig.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/execution/ColumnarBasicPhysicalOperators.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/execution/ColumnarWholeStageCodegenExec.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/expression/ColumnarBinaryOperator.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/expression/ColumnarSorter.scala
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/action_codegen.h
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/actions_impl.cc
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/codegen_node_visitor.cc
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/codegen_node_visitor.h
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/expression_codegen_visitor.cc
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/expression_codegen_visitor.h
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/kernels_ext.cc
Labels: NativeSQL

#2049 [OAP-2408][oap-native-sql]Support SMJ in WholeStageCodeGen
  oap-native-sql/core/src/main/scala/com/intel/oap/ColumnarPlugin.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/execution/CoalesceBatchesExec.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/execution/ColumnarBasicPhysicalOperators.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/execution/ColumnarBroadcastHashJoinExec.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/execution/ColumnarShuffledHashJoinExec.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/execution/ColumnarSortExec.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/execution/ColumnarSortMergeJoinExec.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/execution/ColumnarWholeStageCodegenExec.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/expression/ColumnarSortMergeJoin.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/expression/ColumnarSorter.scala
  oap-native-sql/core/src/main/scala/org/apache/spark/sql/execution/ColumnarBroadcastExchangeExec.scala
  oap-native-sql/core/src/main/scala/org/apache/spark/sql/execution/ColumnarCollapseCodegenStages.scala
  oap-native-sql/cpp/src/CMakeLists.txt
  oap-native-sql/cpp/src/codegen/arrow_compute/expr_visitor_impl.h
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/code_generator_base.h
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/codegen_common.cc
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/codegen_common.h
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/codegen_context.h
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/conditioned_merge_join_kernel.cc
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/conditioned_probe_kernel.cc
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/expression_codegen_visitor.cc
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/expression_codegen_visitor.h
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/kernels_ext.h
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/sort_kernel.cc
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/whole_stage_codegen_kernel.cc
  oap-native-sql/cpp/src/codegen/common/relation.cc
  oap-native-sql/cpp/src/codegen/common/relation_column.h
  oap-native-sql/cpp/src/codegen/common/sort_relation.h
  oap-native-sql/cpp/src/tests/arrow_compute_test_wscg.cc
Labels: NativeSQL

#2063 [OAP-2062][oap-native-sql] fix compare script
  oap-native-sql/tools/process.py
Labels: NativeSQL

#2060 [OAP-1823][oap-native-sql]Update Installation Guide
  oap-data-source/arrow/README.md
  oap-native-sql/README.md
  oap-native-sql/resource/ApacheArrowInstallation.md
  oap-native-sql/resource/Configuration.md
  oap-native-sql/resource/Installation.md
  oap-native-sql/resource/Prerequisite.md
  oap-native-sql/resource/SparkInstallation.md
  oap-native-sql/resource/installation.md
Labels: NativeSQL, OAP 1.0, bug

#2061 [OAP-1856][oap-native-sql] Move ColumnarWholeStageCodeGen out of AQE logic
  oap-native-sql/core/src/main/scala/com/intel/oap/ColumnarPlugin.scala
  oap-native-sql/core/src/main/scala/org/apache/spark/sql/execution/adaptive/AdaptiveSparkPlanExec.scala
Labels: NativeSQL

#2047 [OAP-2046][oap-native-sql] Shuffle write enable FastPFor integer compression
  oap-native-sql/core/src/main/scala/com/intel/oap/ColumnarPluginConfig.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/vectorized/ArrowColumnarBatchSerializer.scala
  oap-native-sql/core/src/main/scala/org/apache/spark/shuffle/ColumnarShuffleWriter.scala
  oap-native-sql/cpp/src/benchmarks/shuffle_split_benchmark.cc
  oap-native-sql/cpp/src/jni/jni_common.h
  oap-native-sql/cpp/src/jni/jni_wrapper.cc
Labels: NativeSQL

#2064 [OAP-1517][oap-native-sql]ColumnarSMJ: adding existence join support
  oap-native-sql/core/src/main/scala/com/intel/oap/execution/ColumnarSortMergeJoinExec.scala
  oap-native-sql/core/src/main/scala/com/intel/oap/expression/ColumnarSortMergeJoin.scala
  oap-native-sql/cpp/src/codegen/arrow_compute/expr_visitor.cc
  oap-native-sql/cpp/src/codegen/arrow_compute/ext/merge_join_kernel.cc
  oap-native-sql/cpp/src/tests/arrow_compute_test_join_smj.cc
Labels: NativeSQL
